version: '2'
services:
    frauddetection-app:
        image: frauddetection
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://frauddetection-mysql:3306/frauddetection?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    frauddetection-mysql:
        extends:
            file: mysql.yml
            service: frauddetection-mysql
